export const positions = [
  { slug: 'head-teacher', title: 'Head Teacher', department: 'Administrative & Leadership', summary: 'Lead curriculum integration, faculty supervision, compliance and community outreach.', qualification: 'Master’s or B.Ed / B.Sc with PGDE; 5–7 years leadership experience; TRCN preferred.', uploads: ['passport', 'cv', 'certificates', 'adminProofs'] },
  { slug: 'secretary', title: 'Secretary', department: 'Administrative & Leadership', summary: 'Manage front-office communications, e-registry, files and executive scheduling.', qualification: 'B.Sc/HND in Secretarial Studies, OTM, English or Mass Communication; 2+ years experience.', uploads: ['passport', 'cv', 'certificates'] },
  { slug: 'ict-officer', title: 'ICT Officer', department: 'Technical & ICT', summary: 'Maintain networks, laboratories, portal infrastructure and digital literacy programmes.', qualification: 'B.Sc/HND in Computer Science, Cybersecurity, Software Engineering or IT.', uploads: ['passport', 'cv', 'certificates', 'techCerts'] },
  { slug: 'teacher', title: 'Teacher', department: 'Academic & Religious Faculty', summary: 'Deliver subject mastery and integrated Deen & Dunya learning.', qualification: 'Ph.D., M.Sc, B.Sc(Ed), B.A(Ed), B.Sc, HND or NCE in a relevant subject.', uploads: ['passport', 'cv', 'certificates', 'transcripts'] },
  { slug: 'security-officer', title: 'Security Officer', department: 'Campus Safety & Operations', summary: 'Direct physical safety, guard details, emergency response and investigations.', qualification: 'Retired military/police, or B.Sc/HND in Criminology/Security Studies; 3+ years supervisory experience.', uploads: ['passport', 'cv', 'serviceCerts', 'id'] },
  { slug: 'security-guard', title: 'Security Guard', department: 'Campus Safety & Operations', summary: 'Enforce access control, visitor screening, patrols and gate logs.', qualification: 'SSCE/WAEC/NECO/Trade Test; physical fitness and basic English/Hausa.', uploads: ['passport', 'cv', 'certificates', 'guarantor'] },
  { slug: 'kitchen-master', title: 'Kitchen Master', department: 'Food Services & Nutrition', summary: 'Oversee institutional kitchen logistics, hygiene, inventories and meal service.', qualification: 'OND/HND in Hospitality & Catering or Food Science; 3+ years institutional kitchen experience.', uploads: ['passport', 'cv', 'certificates', 'foodHygiene'] },
  { slug: 'kitchen-attendant-cook', title: 'Kitchen Attendant / Cook', department: 'Food Services & Nutrition', summary: 'Prepare daily meals, manage ingredients and maintain kitchen sanitation.', qualification: 'SSCE, Trade Test in Catering or relevant apprenticeship; high-volume cooking experience.', uploads: ['passport', 'cv', 'certificates', 'medicalFitness'] },
  { slug: 'messenger', title: 'Messenger / Errand', department: 'Campus Safety & Operations', summary: 'Handle document dispatch, campus errands and supply distribution.', qualification: 'FSLC or SSCE; trustworthy, punctual and numerate.', uploads: ['passport', 'cv', 'certificates', 'guarantor'] },
  { slug: 'cleaner', title: 'Cleaner', department: 'Facilities & Maintenance', summary: 'Maintain sanitation across halls, offices, restrooms and residences.', qualification: 'FSLC or basic literacy; diligence, hygiene awareness and stamina.', uploads: ['passport'] },
  { slug: 'gardener', title: 'Gardener', department: 'Facilities & Maintenance', summary: 'Manage landscaping, lawns, drainage pathways and campus greenery.', qualification: 'Experience in horticulture, landscaping or agricultural maintenance.', uploads: ['passport'] },
  { slug: 'matron', title: 'Matron', department: 'Facilities & Maintenance', summary: 'Oversee female hostels, pastoral care, cleanliness and student welfare.', qualification: 'NCE, RN/RM, Community Health, Guidance & Counseling or Social Work.', uploads: ['passport', 'cv', 'certificates', 'healthCerts'] },
] as const
export type PositionSlug = typeof positions[number]['slug']
export type RecruitmentForm = { position: PositionSlug; fullName: string; phone: string; gender: string; maritalStatus: string; dateOfBirth: string; address: string; nationality: string; state: string; lga: string; qualification: string; specialization: string; secondarySchool: string; institution: string; yearGraduated: string; certificate: string; employed: string; employer: string; currentRole: string; salary: string; experience: string; taughtBefore: string; schoolName: string; subjects: string; yearsTaught: string; adminExperience: string; adminPosition: string; hizbProgress: number; quranCertificate: string; hadithBooks: string[]; arabicFluency: string; attested: boolean; files: Record<string, File | undefined> }
export const initialRecruitment: RecruitmentForm = { position: 'teacher', fullName: '', phone: '+234', gender: '', maritalStatus: '', dateOfBirth: '', address: '', nationality: 'Nigerian', state: '', lga: '', qualification: '', specialization: '', secondarySchool: '', institution: '', yearGraduated: '', certificate: '', employed: '', employer: '', currentRole: '', salary: '', experience: '', taughtBefore: '', schoolName: '', subjects: '', yearsTaught: '', adminExperience: '', adminPosition: '', hizbProgress: 0, quranCertificate: '', hadithBooks: [], arabicFluency: '', attested: false, files: {} }
export const recruitmentSteps = ['Position', 'Personal information', 'Education', 'Experience', 'Faith & language', 'Documents & review']
export const requiresEducation = (p: PositionSlug) => !['cleaner', 'gardener', 'messenger'].includes(p)
export const requiresEmployment = (p: PositionSlug) => !['cleaner', 'gardener'].includes(p)
export const requiresCv = (p: PositionSlug) => !['cleaner', 'gardener'].includes(p)
export const isAcademic = (p: PositionSlug) => ['head-teacher', 'teacher', 'ict-officer', 'secretary'].includes(p)
export const isTeaching = (p: PositionSlug) => ['head-teacher', 'teacher'].includes(p)
export const isHifzul = (p: PositionSlug) => p === 'teacher'
export function getPosition(slug: string) { return positions.find(p => p.slug === slug) ?? positions[3] }
export function applicationReference(position: PositionSlug) { return `ABR-STAFF-${position.slice(0, 3).toUpperCase()}-${Date.now().toString().slice(-6)}` }
export type FieldErrors = Record<string, string>
export const fileLabels: Record<string, string> = { passport: 'Passport photograph', cv: 'CV / Resume', certificates: 'Academic certificates', adminProofs: 'Administrative proof', transcripts: 'Academic transcripts', techCerts: 'Technical certificates', serviceCerts: 'Service / discharge certificates', id: 'Valid ID', guarantor: 'Guarantor form', foodHygiene: 'Food hygiene certificate', medicalFitness: 'Medical fitness certificate', healthCerts: 'Health / professional certificates' }
export const fileAccept = 'image/jpeg,image/png,application/pdf'
export const fileMaxMb = 10
export const hadithBooks = ['Sahih al-Bukhari', 'Sahih Muslim', 'Sunan Abi Dawud', 'Jami at-Tirmidhi', 'Sunan an-Nasai', 'Sunan Ibn Majah', 'Muwatta Malik', 'Musnad Ahmad', 'Riyadh as-Salihin', 'Bulugh al-Maram', 'Al-Arbain an-Nawawiyyah', 'Umdat al-Ahkam', 'Mishkat al-Masabih']

export const nigerianStates: Record<string, string[]> = { Jigawa: ['Auyo','Babura','Birnin Kudu','Biriniwa','Buji','Dutse','Gagarawa','Garki','Gumel','Guri','Gwaram','Gwiwa','Hadejia','Jahun','Kafin Hausa','Kaugama','Kazaure','Kiri Kasama','Kiyawa','Maigatari','Malam Madori','Miga','Ringim','Roni','Sule Tankarkar','Taura','Yankwashi'], Kano: ['Ajingi','Albasu','Bagwai','Bebeji','Bichi','Bunkure','Dala','Dambatta','Dawakin Kudu','Dawakin Tofa','Doguwa','Fagge','Gabasawa','Garko','Garun Mallam','Gaya','Gezawa','Gwale','Gwarzo','Kabo','Kano Municipal','Karaye','Kibiya','Kiru','Kumbotso','Kunchi','Kura','Madobi','Makoda','Minjibir','Nassarawa','Rano','Rimin Gado','Rogo','Shanono','Sumaila','Takai','Tarauni','Tofa','Tsanyawa','Tudun Wada','Ungogo','Warawa','Wudil'], Kaduna: ['Birnin Gwari','Chikun','Giwa','Igabi','Ikara','Jaba','Jema’a','Kachia','Kaduna North','Kaduna South','Kagarko','Kajuru','Kaura','Kauru','Kubau','Kudan','Lere','Makarfi','Sabon Gari','Sanga','Soba','Zangon Kataf','Zaria'], 'Abuja FCT': ['Abaji','Bwari','Gwagwalada','Kuje','Kwali','Municipal Area Council'], Lagos: ['Agege','Ajeromi-Ifelodun','Alimosho','Amuwo-Odofin','Apapa','Badagry','Epe','Eti-Osa','Ibeju-Lekki','Ifako-Ijaiye','Ikeja','Ikorodu','Kosofe','Lagos Island','Lagos Mainland','Mushin','Ojo','Oshodi-Isolo','Shomolu','Surulere'] }
Object.assign(nigerianStates, { Abia: [], Adamawa: [], 'Akwa Ibom': [], Anambra: [], Bauchi: [], Bayelsa: [], Benue: [], Borno: [], 'Cross River': [], Delta: [], Ebonyi: [], Edo: [], Ekiti: [], Enugu: [], Gombe: [], Imo: [], Kogi: [], Kebbi: [], Katsina: [], Kwara: [], Nasarawa: [], Niger: [], Ogun: [], Ondo: [], Osun: [], Oyo: [], Plateau: [], Rivers: [], Sokoto: [], Taraba: [], Yobe: [], Zamfara: [] })
Object.keys(nigerianStates).forEach(state => { if (!nigerianStates[state].length) nigerianStates[state] = ['Other / select LGA'] })
export const years = Array.from({ length: 57 }, (_, i) => String(1970 + i))
export const institutions = ['Ahmadu Bello University', 'Bayero University Kano', 'University of Abuja', 'University of Nigeria Nsukka', 'Federal College of Education', 'Other / Not Listed']
export const certificates = ['Ph.D', 'M.Sc / M.Ed / M.A', 'B.Sc / B.Ed / B.A', 'HND', 'OND / ND', 'NCE', 'SSCE / WAEC / NECO', 'Trade Test / Technical Diploma', 'Other']
export const departments = [...new Set(positions.map(p => p.department))]
export const positionOptions = positions.map(p => p.title)
export const slugFromTitle = (title: string) => positions.find(p => p.title === title)?.slug ?? 'teacher'
export const titleFromSlug = (slug: PositionSlug) => getPosition(slug).title
export const roleUploadKeys = (p: PositionSlug) => getPosition(p).uploads
export const roleFiles = (p: PositionSlug) => roleUploadKeys(p).map(key => ({ key, label: fileLabels[key] ?? key }))
export const stepForPosition = (p: PositionSlug) => isTeaching(p) ? recruitmentSteps : recruitmentSteps.filter(s => s !== 'Faith & language')
export const MAX_FILE_BYTES = 100 * 1024 * 1024
export const MIN_AGE = 18
export const isValidNigerianPhone = (phone: string) => /^(\+234|0)[789][01]\d{8}$/.test(phone.replace(/\s/g, ''))
export const isAdult = (date: string) => Boolean(date) && (Date.now() - new Date(date).getTime()) / 31557600000 >= MIN_AGE
export const emptyErrors: FieldErrors = {}
